name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build project
        run: |
          npm install
          npm run build  # adjust this according to your build command

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist  

  deploy:
    environment:
      name: github-pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
